language: node_js
sudo: false
node_js:
  - 5.10.0

cache:
  directories:
    - node_modules
before_script:
  - git submodule update --init --recursive
  - git submodule foreach git pull origin master
before_install:
  - npm prune
script:
  - 'npm test'