# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  nodejs_version: 5.10.0

install:
  - git submodule update --init --recursive
  - git submodule foreach git pull origin master
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

init:
  - git config --global core.autocrlf false

branches:
  only:
    - master
  except:
    - gh-pages

build: off
deploy: off
