backend:
  name: github
  repo: trkw/tubalcain
  branch: master

public_folder: "/contents"
media_folder: "/contents≥/assets"

collections:
  - name: "post"
    label: "Post"
    folder: "posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}
